const fs = require("fs");
const path = require("path");
const root = "c:/Users/Alex Ventura/Desktop/consulta-tabela-fipe";
const cov = path.join(root, "scripts/datasets/generate-spec-coverage-report.ts");
const covLines = [
  "import fs from 'fs';",
  "import { PATHS } from '../lib/fipe-paths.js';",
  "import { normalizeVehicle } from '../lib/enrichment/matching-engine.js';",
  "import type { NormalizedVehicle } from '../lib/enrichment/types.js';",
  "",
  "type FieldStats = { preenchidos: number; pct: number; meta: number; atingiu: boolean };",
  "",
  "function pct(n: number, total: number) { return Math.round((n / total) * 10000) / 100; }",
  "function fieldStats(n: number, total: number, meta: number): FieldStats {",
  "  const p = pct(n, total);",
  "  return { preenchidos: n, pct: p, meta, atingiu: p >= meta };",
  "}",
  "",
  "async function main() {",
  "  const input = fs.existsSync(PATHS.normalizedVeiculos) ? PATHS.normalizedVeiculos : PATHS.srcVeiculos;",
  "  const vehicles = (JSON.parse(fs.readFileSync(input, 'utf-8')) as NormalizedVehicle[]).map((v) => normalizeVehicle(v));",
  "  const master = fs.existsSync(PATHS.specsMaster)",
  "    ? (JSON.parse(fs.readFileSync(PATHS.specsMaster, 'utf-8')) as { veiculos: Record<string, Record<string, unknown>> }).veiculos",
  "    : {};",
  "  const total = vehicles.length;",
  "  let p = 0, t = 0, tr = 0, pm = 0;",
  "  const byMarca = new Map();",
  "  for (const v of vehicles) {",
  "    const s = master[v.vehicleId];",
  "    const m = byMarca.get(v.marca) ?? { total: 0, p: 0, t: 0, tr: 0, pm: 0 };",
  "    m.total++;",
  "    if (s?.potencia) { p++; m.p++; }",
  "    if (s?.torque) { t++; m.t++; }",
  "    if (s?.transmissao) { tr++; m.tr++; }",
  "    if (s?.porta_malas) { pm++; m.pm++; }",
  "    byMarca.set(v.marca, m);",
  "  }",
  "  const cobertura = { potencia: fieldStats(p, total, 70), torque: fieldStats(t, total, 70), transmissao: fieldStats(tr, total, 70), porta_malas: fieldStats(pm, total, 50) };",
  "  const report = { geradoEm: new Date().toISOString(), totalVeiculos: total, cobertura, marcas: byMarca.size };",
  "  fs.mkdirSync(PATHS.reportsRoot, { recursive: true });",
  "  fs.writeFileSync(PATHS.specCoverageReport, JSON.stringify(report, null, 2));",
  "  console.log(JSON.stringify({ cobertura, marcas: byMarca.size }));",
  "}",
  "main().catch((e) => { console.error(e); process.exit(1); });",
  "",
];
fs.writeFileSync(cov, covLines.join("\n"), "utf8");
console.log("coverage", fs.statSync(cov).size);

const build = path.join(root, "scripts/datasets/build-specs-master.ts");
const buildLines = [
  "import fs from 'fs';",
  "import path from 'path';",
  "import { PATHS } from '../lib/fipe-paths.js';",
  "import { normalizeVehicle, normalizeText } from '../lib/enrichment/matching-engine.js';",
  "import { computeMatchingScore } from '../lib/enrichment/matching-score.js';",
  "import { loadGenerationsCatalog, resolveGeneration, sameGeneration } from '../lib/enrichment/generation-match.js';",
  "import { inferSpecsFromFipeModel } from '../lib/enrichment/infer-fipe-specs.js';",
  "import { marcaSlug } from '../lib/fipe-slug.js';",
  "import type { NormalizedVehicle } from '../lib/enrichment/types.js';",
  "export interface SpecMasterRecord { vehicle_uid: string; vehicle_id: string; potencia?: number; torque?: number; transmissao?: string; porta_malas?: number; tanque?: number; confidence?: number; fonte: string; capturado_em: string; metodo?: string; geracao_id?: string; }",
  "type PS = Partial<Pick<SpecMasterRecord, 'potencia' | 'torque' | 'transmissao' | 'porta_malas' | 'tanque' | 'geracao_id'>>;",
  "interface MfrRow { marca: string; modelo: string; ano?: number; potenciaCv?: number; torqueNm?: number; cambio?: string; portaMalasL?: number; tanqueL?: number; fonte?: string; }",
  "const MATCH_OEM_PAGE = 0.68; const MATCH_PROPAGATE = 0.55;",
  "function oemCatalogScore(fipe: { marca: string; modelo: string; ano: number }, row: MfrRow): number {",
  "  if (marcaSlug(fipe.marca) !== marcaSlug(row.marca)) return 0;",
  "  const fm = normalizeText(fipe.modelo); const rm = normalizeText(row.modelo);",
  "  if (!rm || rm.length < 2) return 0;",
  "  if (!fm.includes(rm) && !fm.startsWith(rm.split(' ')[0] ?? '')) return 0;",
  "  const anoDiff = row.ano ? Math.abs(fipe.ano - row.ano) : 0; if (anoDiff > 3) return 0;",
  "  return Math.min(0.95, MATCH_OEM_PAGE + (anoDiff === 0 ? 0.12 : anoDiff === 1 ? 0.08 : 0.04));",
  "}",
  "function manufacturerScore(fipe: { marca: string; modelo: string; ano: number }, row: MfrRow): number {",
  "  return Math.max(computeMatchingScore(fipe, { marca: row.marca, modelo: row.modelo, ano: row.ano }), oemCatalogScore(fipe, row));",
  "}",
  "function loadVehicles(): NormalizedVehicle[] { const file = fs.existsSync(PATHS.normalizedVeiculos) ? PATHS.normalizedVeiculos : PATHS.srcVeiculos; return (JSON.parse(fs.readFileSync(file, 'utf-8')) as NormalizedVehicle[]).map((v) => normalizeVehicle(v)); }",
  "function loadManufacturers(): MfrRow[] { const rows: MfrRow[] = []; if (!fs.existsSync(PATHS.rawManufacturers)) return rows; for (const f of fs.readdirSync(PATHS.rawManufacturers).filter((x) => x.endsWith('.json') && x !== 'crawl-log.json')) { const parsed = JSON.parse(fs.readFileSync(path.join(PATHS.rawManufacturers, f), 'utf-8')); if (Array.isArray(parsed)) rows.push(...parsed); } return rows; }",
  "function merge(a: PS, b: PS): PS { return { ...a, ...Object.fromEntries(Object.entries(b).filter(([, v]) => v != null)) }; }",
  "function fromMfr(r: MfrRow): PS { return { potencia: r.potenciaCv, torque: r.torqueNm, transmissao: r.cambio, porta_malas: r.portaMalasL, tanque: r.tanqueL }; }",
  "function fromInfer(modelo: string): PS { const i = inferSpecsFromFipeModel(modelo); return { potencia: i.potenciaCv ?? undefined, torque: i.torqueNm ?? undefined, transmissao: i.cambio ?? undefined }; }",
  "function fromStatic(specs?: Record<string, unknown>): PS { if (!specs) return {}; const pot = specs.potencia as { valor?: number } | undefined; const tor = specs.torque as { valor?: number } | undefined; const pm = specs.portaMalas as { valor?: number } | undefined; return { potencia: pot?.valor, torque: tor?.valor, transmissao: (specs.cambio as string | undefined) ?? undefined, porta_malas: pm?.valor, tanque: (specs.tanque as { valor?: number } | undefined)?.valor }; }",
  "function hasSpec(s: PS): boolean { return !!(s.potencia || s.torque || s.transmissao || s.porta_malas); }",
  "function toRec(v: NormalizedVehicle, s: PS, confidence: number, fonte: string, metodo: string): SpecMasterRecord { return { vehicle_uid: v.vehicleUid ?? v.vehicleId, vehicle_id: v.vehicleId, ...s, confidence, fonte, capturado_em: new Date().toISOString(), metodo }; }",
  "async function main() {",
  "  const vehicles = loadVehicles(); const mfrRows = loadManufacturers();",
  "  const staticCat = fs.existsSync(PATHS.staticSpecsCatalog) ? JSON.parse(fs.readFileSync(PATHS.staticSpecsCatalog, 'utf-8')) : {};",
  "  const genCatalog = loadGenerationsCatalog(); const master = new Map<string, SpecMasterRecord>();",
  "  const byFamily = new Map<string, NormalizedVehicle[]>();",
  "  for (const v of vehicles) { const fk = v.marcaSlug + '|' + (v.modeloSlug.split('-')[0] ?? v.modeloSlug); (byFamily.get(fk) ?? byFamily.set(fk, []).get(fk)!).push(v); }",
  "  for (const v of vehicles) {",
  "    let spec: PS = {}; let confidence = 0; let fonte = 'nenhuma'; let metodo = 'fipe_inferido';",
  "    spec = merge(spec, fromStatic(staticCat[v.vehicleId]?.specs)); if (hasSpec(spec)) { confidence = 0.65; fonte = 'static-catalog'; metodo = 'static_catalog'; }",
  "    const inf = fromInfer(v.modelo); if (inf.potencia || inf.transmissao || inf.torque) { spec = merge(spec, inf); confidence = Math.max(confidence, inf.potencia ? 0.55 : 0.45); if (fonte === 'nenhuma') { fonte = 'fipe-modelo'; metodo = 'fipe_inferido'; } }",
  "    let best = 0; let bestRow: MfrRow | null = null;",
  "    for (const row of mfrRows) { const sc = manufacturerScore({ marca: v.marca, modelo: v.modelo, ano: v.ano }, row); if (sc > best) { best = sc; bestRow = row; } }",
  "    if (bestRow && best >= MATCH_OEM_PAGE) { spec = merge(spec, fromMfr(bestRow)); confidence = Math.max(confidence, best); fonte = bestRow.fonte ?? 'fabricante'; metodo = 'fabricante'; }",
  "    const gen = resolveGeneration(v.marca, v.modeloSlug, v.ano, genCatalog)?.id; if (gen) spec.geracao_id = gen;",
  "    if (hasSpec(spec)) master.set(v.vehicleId, toRec(v, spec, confidence, fonte, metodo));",
  "  }",
  "  const seeds = [...master.entries()].filter(([, r]) => (r.confidence ?? 0) >= 0.7 && r.metodo === 'fabricante');",
  "  for (const [seedId, seedRec] of seeds) {",
  "    const seedV = vehicles.find((x) => x.vehicleId === seedId); if (!seedV) continue;",
  "    const peers = byFamily.get(seedV.marcaSlug + '|' + (seedV.modeloSlug.split('-')[0] ?? seedV.modeloSlug)) ?? [];",
  "    for (const peer of peers) {",
  "      if (peer.vehicleId === seedId) continue; if (!sameGeneration(peer.marca, peer.modeloSlug, peer.ano, seedV.ano, genCatalog)) continue;",
  "      const ex = master.get(peer.vehicleId); if (ex && (ex.confidence ?? 0) >= 0.65) continue;",
  "      const conf = Math.max(0.45, (seedRec.confidence ?? 0.7) - Math.abs(peer.ano - seedV.ano) * 0.08);",
  "      if (conf >= MATCH_PROPAGATE) master.set(peer.vehicleId, toRec(peer, { potencia: seedRec.potencia, torque: seedRec.torque, transmissao: seedRec.transmissao, porta_malas: seedRec.porta_malas, tanque: seedRec.tanque, geracao_id: seedRec.geracao_id }, conf, seedRec.fonte + ' (propagado)', 'propagacao_geracao'));",
  "    }",
  "  }",
  "  fs.mkdirSync(PATHS.generatedRoot, { recursive: true });",
  "  fs.writeFileSync(PATHS.specsMaster, JSON.stringify({ geradoEm: new Date().toISOString(), total: master.size, veiculos: Object.fromEntries(master) }, null, 2));",
  "  console.log(JSON.stringify({ total: master.size, fabricante: seeds.length }));",
  "}",
  "main().catch((e) => { console.error(e); process.exit(1); });",
  "",
];
fs.writeFileSync(build, buildLines.join("\n"), "utf8");
console.log("build", fs.statSync(build).size);